mmc: core: Eliminate deprecated BKOPS definition usage
The definition of `mmc_card_doing_bkops` has been dropped in
upstream with commit aae3dc5 ("mmc: core: Cleanup BKOPS support").
It's now an implicit declaration at mmc_is_valid_state_for_clk_scaling().

Honoring upstream's changes, drop the check of `mmc_card_doing_bkops` at
mmc_is_valid_state_for_clk_scaling().

This fixes the following compilation error:

../drivers/mmc/core/core.c:337:4: error: implicit declaration of function 'mmc_card_doing_bkops' [-Werror,-Wimplicit-function-declaration]
                        mmc_card_doing_bkops(card))))
                        ^

Fixes: aae3dc5 ("mmc: core: Cleanup BKOPS support")
Change-Id: I7613a8f719ef58e1ece1e736d3528327187ecaa1
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>